Modified files for handling multiple iscsi session logout
hpe-storage/common-host-libs pull request #138
Opened 2020-11-12 07:42 UTC by bhagyashree-sarawate

Problem statement:
There was an issue with iscsiadm logout step as part of the cleanup of deletedevices in NodeUnstageVolume. It deletes and logs out only 1 target node.
As part of nodeStageVolume, CSI creates deviceInfo.json and writes staging device information in it. But, it writes only one iscsiTarget info in it rather than a list

The mentioned PR has the fix for the multiple iscsi session logout.
It now writes the list of the iscsiTargets in deviceInfo.json file so that it logs out all the iscsi session.

2020-11-12 22:54 UTC, raunakkumar requested changes
Please make the suggested changes and could we have a private image to be run by nimble automation team to make sure there is no regression?

2020-11-12 22:54 UTC, raunakkumar commented on model/types.go
> +	IscsiTarget     []*IscsiTarget `json:"iscsi_target,omitempty"`
modify to 
```IscsiTargets     []*IscsiTarget `json:"iscsi_targets,omitempty"` ``` ?

2020-11-12 22:54 UTC, raunakkumar commented on linux/iscsi.go
> +	if iscsiTargets != nil {
just return `iscsiTargets, nil` instead of checking the if condition

2020-11-12 22:54 UTC, raunakkumar commented on linux/iscsi.go
> +func iscsiGetTargetOfDevice(dev *model.Device) (target []*model.IscsiTarget, err error) {
rename this method to `iscsiGetTargetsOfDevice`

2020-11-12 22:54 UTC, raunakkumar commented on linux/iscsi.go
> +	if iscsiTargets != nil {
The caller of this method would also need to be modified. 
Currently we set the device iscsiTarget but now we need to refer to iscsiTargets[0] atleast for non 3Pardata
```iscsiTarget, err := iscsiGetTargetOfDevice(device)
				if err != nil {
					log.Debugf("unable to get iscsi target for device %s. Error: %s", device.Pathname, err.Error())
					continue
					// continue with other devices, might be in offline state and IscsiTarget will be nil for this device
				}
				if iscsiTarget != nil {
					device.IscsiTarget = iscsiTarget
				}
			}
```

2020-11-17 07:58 UTC, sneharai4 approved these changes

2020-11-26 04:39 UTC, wdurairaj approved these changes
Changes looks fine for me.

2020-12-01 16:15 UTC, raunakkumar approved these changes

2020-12-01 16:15 UTC, merged